###CREATE A NEW USER
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email" : "testandosenha@gmail.com",
  "password": "leite"
}

###LOGIN
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email" : "testandosenha@gmail.com",
  "password": "leite"
}

###FIND USER FOR ID
GET http://localhost:3000/auth/user/4

###FIND ALL USERS
GET http://localhost:3000/auth/all

###Find All user com EMAIL
GET http://localhost:3000/auth?email=vineeee@gmail.com

###DELETE USER
DELETE http://localhost:3000/auth/8

###UPDATE USER
PATCH http://localhost:3000/auth/4
content-type: application/json

{
  "email":"leite@gmail.com",
  "password": "10019"
}
