###CREATE A NEW USER
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email" : "text@text.com",
  "password": "leite"
}

###LOGIN
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email" : "text@text.com",
  "password": "leite"
}

### Get the currently singed in user
GET http://localhost:3000/auth/whoami

###Sign out
POST http://localhost:3000/auth/signout

###FIND USER FOR ID
GET http://localhost:3000/auth/user/4

###FIND ALL USERS
GET http://localhost:3000/auth/all

###Find All user com EMAIL
GET http://localhost:3000/auth?email=vineeee@gmail.com

###DELETE USER
DELETE http://localhost:3000/auth/8

###UPDATE USER
PATCH http://localhost:3000/auth/4
content-type: application/json

{
  "email":"leite@gmail.com",
  "password": "10019"
}

### Set a Color
Get http://localhost:3000/auth/colors/red

### Get the sessions
Get http://localhost:3000/auth/sessions